### ISSUE TITLE
Can't do `tuist build` to run the project

### ISSUE THREAD

**Issue by nikivdev** [Dimillian/IcySky#6]
<img width="1172" alt="image" src="https://github.com/user-attachments/assets/7e1ce73c-8b35-4533-a682-2e2791d7f844">

I thought this was the flow you have to do with `tuist`. Then do `tuist generate` but it fails on `tuist build`, unclear why.

readme.md doesn't mention how to run the project

**Comment by nikivdev** [comment]
if I try build it without `tuist build` thing, just using Xcode, I get:

<img width="961" alt="image" src="https://github.com/user-attachments/assets/2c2b1e8e-ece8-4b37-aa42-fb4eba4f6041">

**Comment by nikivdev** [comment]
I also tried building it in Cursor itself after reading article:

https://dimillian.medium.com/how-to-use-cursor-for-ios-development-54b912c23941

but it's unclear what to do here:

<img width="258" alt="image" src="https://github.com/user-attachments/assets/077e0064-21c6-43c4-9350-61b5e9f22fd3">

**Comment by Dimillian** [comment]
It's not a tuist project. Run IcySky scheme, from Cursor or Xcode, it should work.
